import { CatalogModel, DefectItem } from "./types";
import catalogModelsData from "@/data/catalog-models.json";

export const CATALOG_MODELS: CatalogModel[] = catalogModelsData as CatalogModel[];

export const DEFECTS_LIST: DefectItem[] = [
  {
    id: "screen_scratches",
    title: "Screen Scratches",
    description: "Surface scratches or glass cracks",
    category: "display",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB39A3hszCztMdNbVLDie9_EEWVRZR1p3a0KiHGFdDIjQsJMBvfsjrL43azFNjFmto6Xa2GLBqwgBl1Bu6UZow0mDG87Qiaq3brgCSDzZmSTa4mVnU5zqJOWZpbwXCtGU1ac8Vx4W53QxoIDDVaIYquF1ycoj9RCwjUZU3IC3umJ5EWBMHEAP_FY0K1UXFiqTfKNK-4ibvYXyntdgvBdPkzrX7Rxs0o6Y10R0kERAt8jUABAsyQqy0VFmeEeR6fMzbb5A",
  },
  {
    id: "dead_spots",
    title: "Dead Spots / Lines",
    description: "Dead pixels, lines, or discoloration",
    category: "display",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAlbFG4XGhvA7bZN6T9v8zD_VcjoOJkxFGhvmWPWlyndQs1eEcLLeO-HVu1uLrj6vMLlXCrVCVfToNz0UXFf6GmjTNYK4AXVjSgF-8k6i4aKMsJ6XMmHgHKO0eDpUxBz0jAplFtiPB3dYdiJgMxFqffnHg4xf96nxt3ljHlPHv8_0GZM2jVZCNKLhsGm7fs7FEJbxDBh3in_T3akgWEfaDUFmspFxDZoQBuEJXclBIfXXfoLq1KAIfK1FUmvBxoYo1VBw",
  },
  {
    id: "touch_issues",
    title: "Touch Issues",
    description: "Unresponsive touch or ghost touches",
    category: "display",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAvQ3TTwoXcqekIt_Otd98zs_QjnPVs9j_avMRo748w8ydeF3viCuFFTy-VD3l4dfa6KmfbiuCQMk5ZMZt6x7dh7gpMSX2h2QoXa1AKfBujUzfg8HAbx59ytXzA2plnypEPel-5wR1p_Fp0UqnM5bDde3grzdq3XoClaEtT79HX_MgHlDTtXxmD_-Gn95vIONnQUKh6Xltp5LSLG4RXlvNyKlxhXZNKpVo2dCLZg_4XjJQEyzEi-tac7bvcFrZ2mQ-YAQ",
  },
  {
    id: "face_id",
    title: "Face ID / Biometrics",
    description: "Biometric sensor not working",
    category: "sensors",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCmdpbHaZIbG3XR60a6H8X2IYZ1A_-UKM0YIn_j6WEmVhmIObQ_GkysyC8oT-Nik6CymtI6EPg7_IUfujE5CAYIaPO5XVpAl1ZsJt7lyHPXitNuVSlPygrSSmMVh6FU20YmnY4oc0g34KNd6Rn8yo971rrYhzLwFRGAbhDZFh08k9Lc2Nf1HL5405SyjsS7TiixTZTHCHjgT-DfCH4vUunCiCoxwcRwIposf-jwNIWWFpNHLtACu495Fzj8nTeqNoKKsw",
  },
  {
    id: "proximity_sensor",
    title: "Proximity Sensor",
    description: "Screen stays on during calls",
    category: "sensors",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAZ05cOLV-zwaGIkQvspvEH6BwfnC9P8oQc-3lf1kae6fdXwGnHeaXbEebtAqV9rV5HL1SJAKj3d3iQ5tz0aWbo2nRlKk3A0CnWwIjbTaHks2bI9K3CMCbFoiiwVQE4PJY5rIZdmEJQ2MvF5CukVszweCjmBIt08xhTVygLxKsMZPtKzG7dJNaeJn7umsP10CrUXgxjO5ehSkfYU8ygesaGwoZ9SgcJQUGHFJRWFejF8l-f8-g9NNxsW0cWfaOqzdokRA",
  },
  {
    id: "front_camera",
    title: "Front Camera",
    description: "Front camera blurry or black screen",
    category: "sensors",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAszGUh7Naq0Xh3am0XVD5LFQ3dU_nputpfrRLQLJGBzHj0oBVQtlRsPbKFC-cYI0uGXNXKOuYzbeiMeSB1Tlt5GsJNHvSXjQv4TKetjCn-0ESuNKAWhv2aes05umTqh_CVLWYqTm2yVMwQQsru4WziKUX7wtnrTFMBZCxWz_ioTRa7p5QHerAjk-GOyp0V5zcH-wjCnLK1YodfWZHjJPB2BeN9Xhbfsvknvi4eKnJx7eVQHQ5lTzX3kbEMnk-4ckYt2Q",
  },
  {
    id: "back_camera",
    title: "Back Camera",
    description: "Rear camera blurry, shaky, or failing",
    category: "sensors",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC4rfEfOcYnjuJTjJKzO0W_YaFN-U2YGtwUaODfIOy4vJiAoF_XyMAc6QrqdkteLvFgRt8BhLmKdcbrq1eZJpOcAIHDn59UFn0d9BKd68BQmZaiJ7mFVKXVBSxXj-YE_etoE-OHCNZ6z3ETZWibl7zxQkxaKwkmRAA-3NHkPzM-yOGYBVO5_XdpiXBtddXJtosIy7BfklLK948MSRhzqpFMQvJVweBf1DCsPC0p13w-FslTlgp9eCFwOmCYp-oC2oB_aQ",
  },
  {
    id: "camera_glass",
    title: "Camera Glass Cracked",
    description: "Cracked lens cover",
    category: "body",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCI1JIZfcg-Ee0gD2nBhlFU4Y4Cbz8_xrPNy_BFXoVJq308794nc5MAp3UpRFf8cUraj0YVFyKA_Y4hwg66ysoRbfV0BtmCJLgrJy54gFUdmcgenTKSeaiIJ1SqSsJBFGLwIUmWqCt2zyr1okvmrgdYxWsr9ykrpo8nA9TXaoL3phQavqakeKYhJ2LK6ARmDre1pJOTiqaSHOutQqKFpdE0fBNkhCBXi-YAhKxDhuK0pgLKkxbtrjw1vw96vzEJwl-geA",
  },
  {
    id: "battery_degraded",
    title: "Battery Degraded",
    description: "Rapid drain or poor battery health",
    category: "power",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD_EIQ93izEhesqVgOUo1j5VVu6f6vwSWw2zs317Vest3symSZBjg2rEy2_2C5e4HGvOpu-2Vvd6WGtkbaX1BQUryNpD_jzRYo1AIFBy_G3LUVg_J_EXb8Q4RMxfkME77EqFO96Bc1jH2oXjDFpeniL-bD1vkHAriu_bxjmU16fRY9YA5BhV5PsoNW6JS25MqZRz8Esy4vEyHlGvsnqxDBtvyAnmmqHG9eaKKVboDya_i8DgEt0phRoRrNMg8HNGiKvjg",
  },
  {
    id: "charging_port",
    title: "Charging Port",
    description: "Loose connection or won't charge",
    category: "power",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCk4bbiwUne6IC7m9clizOw3K_t4T3a54JMzE9WoCeMaDpJgqJUlVExbBX0Gc3hkMe-d7tovjVGz8AXdSTlAaXKXWKZUxYaH35_68Zr4sxP6Lr23iC4eGH08JJ9ax0H_7P6RYY_oWM2Q91jkxvaeOoOeyr463fZcjotgFKZvdvjG_VgKwmydywSZc4BOSLDjHC2CWC1eNMoC0iEQXPuIR8nhjzXenmkyTz7IFDexWsLoPT-c8LZyMOdGEmyxxzg1SKT4g",
  },
  {
    id: "speaker_issue",
    title: "Speaker Issue",
    description: "Distorted or no sound",
    category: "audio",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCwCgOmLLpScTueGte4lE5ar4eXxUIRqGefJfIZVbr4zb-EAphUANqmdB_ismDaEMoaGizJIaJxRszpCUVwnHj9sJ8Ie9Eaof90yxKf7av3vZxbLwe58UhfTgkW9oDBmPDvc49Ae5lrhqx8C8m6X4a8axnc6e75KnR0n9D8Ur0chBvQGUEoaBJ6issBrbOqMMzyE0h9IPlipWw5l8VixNdq0ppK4YwIt7I-cJR0junkZxO9JPXcrqrGRhxzHSkokhnXJQ",
  },
  {
    id: "microphone",
    title: "Microphone",
    description: "Callers can't hear you clearly",
    category: "audio",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCqfCRxn8F9k1at0EbE9bw632i2hiLuIKVEnHVfHbbAtPYpIRyyDZZECSVMpSP9kEnVw27_7JT7KKGW1l3hU1c4LNHGWkfDmWQejBZW9tPkLW3r2pJ0yfBWTJqkpbU1ENB0UOGBBrbzSiJrHblzm1p72PhjOQWuz2huiqb-9-GMGFsSlHXQ6BFuRrYZVhNsUaqJzDFQrT_WwhkKl_rvie9mQc64iy8YuiIzzzepFRs2qSbpA3UaQvPzND_HqMWHi5mybg",
  },
  {
    id: "earpiece",
    title: "Earpiece Fault",
    description: "Low or muffled in-call audio",
    category: "audio",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCe7jjUcu809TFcH5TMl2Clh4RpPKN948FJaePitaJB3L5HZv0cUIsXBmAZKDN95C_qmfkhTlUJG3t0JIsTc_e3TOGg5BbHvc2thj6ntx-hCU88S2f5UmQHBti8v-d3TUDQd68MdMP7bqzYyJHt9wczndg1DmIa80jApK5plh9CxextKEWaAYyJKaNKltsgOBEv2eOa_TFD1Q9YFOq1wwQKRa3x0v6t0YJ5xTc6QkrMf2dS6V8JKbdtmozbVCrrwYbQMw",
  },
  {
    id: "volume_buttons",
    title: "Volume Buttons",
    description: "Buttons stuck or not responding",
    category: "body",
    severity: "MINOR",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCUicY5SpDLR6lD7AvOnjsT15TzEdZUzhYoEayVw3DozvAhF_eHg-ELw7FoAc2j35KvGcWdiGAdz201cG9dpb6X-ZX-zzraMEknJ4kpbXQpcauDt8YmUezFBxlsv8WWsJD63LKzB4CK3RdPEcFezglLcyezZxor8p27zJx1Ct5H8OhgHGVHDnap2OKzSdW3UIc4bTFSkY2lcYkzadNO0CCU0Sunib34JcsLZ5NDCg7NS2Tl4_D2u2U6hTpJ0H3Qxh2VGA",
  },
  {
    id: "power_button",
    title: "Power Button",
    description: "Power key stuck or unresponsive",
    category: "body",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAtmnqYxCpN-NtTj_kcRKDKC4msthvMN-TMzT6hUkKL4Zx1M5aH_Q6sKe_URhl1c7eJucC6tRVRpI31taeVELJMgDU8JcfU7CJrKbCr5-cbmr7mnVFS6sXofRgocQJFErIHrcLdGBxBzZ5SiCiiQf8thlZtsUhEYF1AET59NC72PISv2DOAaCRA6T_YHt4lHSGynR8iGG0_4tFO_XLcKf4oxcZqH_j0Yfor2eZq8cEX4BbOzu65qoe-aFyfvGICNvpClQ",
  },
  {
    id: "silent_switch",
    title: "Silent Switch",
    description: "Switch loose or not toggling",
    category: "body",
    severity: "MINOR",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDC7Yn0e87q6goh3r8GaejcjTZkv7uC8DxNb3tY35LYa2Xe2LJefASl_BZhg5v5XDs3ocsKR7X3NLqomsSIO9vWmMLLikTUbLzNKGXzSTCBoDjZfeQANsnS2lny0HTGB2juy2Dpr5Qhaq1xaQagJS0CpBJSSQXLIndoDIQc5680T3iCSYEW9DOkZAKGndvagiGwj8JeyuZmnpuId-Jl0v8-c-20b_83-b2tdWm_srAzbr3rx37Yt2ufpo8fNGVYFGwhHw",
  },
  {
    id: "vibration_motor",
    title: "Vibration Motor",
    description: "Rattling or no vibration",
    category: "body",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQG05jtS-IvVb8kltAOaGQLWRWTMpV7pAuwVMxQjwm7A1M2ppOAzTPe5oRKHo1Hz1s6Umv62kfzejzz6NID9Rju_hk2gO8sLRPFmBEjVQN8RGez8NgxHsJInF00YJ4EMdmwUD1WB8eKUTynLSWUSSQu0ZQaoC5RmORNtQFX7SzjrWfpyVDMsUio49gbQjhEJugWGUakJmm_o-ZQv7wT_qmvLwjontEsZvHeEse12NBtTvz-UqNRzT6jh_buS2ioqXbWg",
  },
  {
    id: "wifi_issue",
    title: "Wi-Fi Issue",
    description: "Frequent disconnects or won't connect",
    category: "power",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDoFlQ4TKzY3QDD5_gdm9rwQkay6AHoKDsd-wsxezUw4aXdemavXRmfrXH8dmqwmjs6IwGMRMhb3slhX6q9uv7Z0vZTiNGlGKyBufBQzWZaHLNi6-tKgA7H9YuNblB_Ozdvxq2VHfOtuQugtiP7GaPVAcilR6hEhfJodqSuzG2vqdsjKlnua3sY1vrTITue44A2YLyZwEDN0NPuZqVMOsfP0l6MdRF0_pvMNBIoTyqsZYL6Cm0VmLWj_PDcOCeCexX7jw",
  },
  {
    id: "bluetooth_failure",
    title: "Bluetooth Failure",
    description: "Won't pair or discover accessories",
    category: "power",
    severity: "MODERATE",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuC7rAE-YIrbZYIqIdd9Usg_AdKAhhdSa75kh3bLhQT9ORy0Aoj_tVSizPdrIi_Y38i0wGcRzzzCRkKS_byhnMQHsfKrwUCS1cvpt52KYbPFan7LUjt7wWxPHeDrsSmO7Q9DRIqgIY1delCcWSPPAYLDitanRrTEdHs3QN8j8q-SCxc8_dcTTU-et3z8D5Tl3rDYpqKimD1dhrX0UXIRdPDQDhp-n3UERtckCPA8QTFJ7xMcSHsUDm4ioLTq_I8uleHCSA",
  },
  {
    id: "scratch_dent_body",
    title: "Body Scratches & Dents",
    description: "Minor chassis scuffs, nicks, or small body dents",
    category: "body",
    severity: "MINOR",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB39A3hszCztMdNbVLDie9_EEWVRZR1p3a0KiHGFdDIjQsJMBvfsjrL43azFNjFmto6Xa2GLBqwgBl1Bu6UZow0mDG87Qiaq3brgCSDzZmSTa4mVnU5zqJOWZpbwXCtGU1ac8Vx4W53QxoIDDVaIYquF1ycoj9RCwjUZU3IC3umJ5EWBMHEAP_FY0K1UXFiqTfKNK-4ibvYXyntdgvBdPkzrX7Rxs0o6Y10R0kERAt8jUABAsyQqy0VFmeEeR6fMzbb5A",
  },
  {
    id: "panel_missing_broken",
    title: "Back Glass / Panel Broken",
    description: "Back glass cracked or frame panel missing",
    category: "body",
    severity: "CRITICAL",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCI1JIZfcg-Ee0gD2nBhlFU4Y4Cbz8_xrPNy_BFXoVJq308794nc5MAp3UpRFf8cUraj0YVFyKA_Y4hwg66ysoRbfV0BtmCJLgrJy54gFUdmcgenTKSeaiIJ1SqSsJBFGLwIUmWqCt2zyr1okvmrgdYxWsr9ykrpo8nA9TXaoL3phQavqakeKYhJ2LK6ARmDre1pJOTiqaSHOutQqKFpdE0fBNkhCBXi-YAhKxDhuK0pgLKkxbtrjw1vw96vzEJwl-geA",
  },
];
